### ISSUE TITLE
Error building from source distribution

### ISSUE THREAD

**Issue by blowekamp** [scikit-build/cmake-python-distributions#19]
I setup a new python environment with the following:

```bash
mkvirtualenv cmake-test
pip install -U pip 
pip install -U setuptools
pip install --no-binary ":all:" scikit-build
```

When I tried to install cmake from the source I get the following error:

```
$ pip install --no-binary ":all:" cmake
Collecting cmake
  Using cached cmake-0.6.0.tar.gz
Skipping bdist_wheel for cmake, due to binaries being disabled for it.
Installing collected packages: cmake
  Running setup.py install for cmake ... error
    Complete output from command /home/blowekamp/.virtualenvs/cmake-test/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-n6tqv3/cmake/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-WtxxK2-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/blowekamp/.virtualenvs/cmake-test/include/site/python2.7/cmake:
    cmake version 3.6.2
    
    CMake suite maintained and supported by Kitware (kitware.com/cmake).
    
    
    --------------------------------------------------------------------------------
    -- Trying "Ninja" generator
    --------------------------------
    ---------------------------
    ----------------------
    -----------------
    ------------
    -------
    --
    -- The CXX compiler identification is GNU 4.8.5
    -- Check for working CXX compiler: /usr/lib64/ccache/c++
    -- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- The C compiler identification is GNU 4.8.5
    -- Check for working C compiler: /usr/lib64/ccache/cc
    -- Check for working C compiler: /usr/lib64/ccache/cc -- works
    -- Detecting C compiler ABI info
    -- Detecting C compiler ABI info - done
    -- Detecting C compile features
    -- Detecting C compile features - done
    -- Configuring done
    -- Generating done
    -- Build files have been written to: /tmp/pip-build-n6tqv3/cmake/_cmake_test_compile/build
    --
    -------
    ------------
    -----------------
    ----------------------
    ---------------------------
    --------------------------------
    -- Trying "Ninja" generator - success
    --------------------------------------------------------------------------------
    
    -- The CXX compiler identification is GNU 4.8.5
    -- Check for working CXX compiler: /usr/lib64/ccache/c++
    -- Check for working CXX compiler: /usr/lib64/ccache/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    -- ***************************************************
    -- Build CMake from source: ON
    -- ***************************************************
    CMake Error at CMakeLists.txt:35 (include):
      include could not find load file:
    
        /tmp/pip-build-n6tqv3/cmake/CMakeUrls.cmake
    
    
    CMake Error at CMakeLists.txt:42 (message):
      Failed to determine which archive to download: 'unix_source_url' variable
      is not defined
    Call Stack (most recent call first):
      CMakeLists.txt:53 (check_archive_var)
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-build-n6tqv3/cmake/_skbuild/cmake-build/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "/home/blowekamp/.virtualenvs/cmake-test/lib/python2.7/site-packages/skbuild/setuptools_wrap.py", line 408, in setup
        cmake_install_dir=skbuild_kw['cmake_install_dir'])
      File "/home/blowekamp/.virtualenvs/cmake-test/lib/python2.7/site-packages/skbuild/cmaker.py", line 161, in configure
        os.path.abspath(CMAKE_BUILD_DIR)))
    
    An error occurred while configuring with CMake.
      Command:
        "cmake" "/tmp/pip-build-n6tqv3/cmake" "-G" "Ninja" "-DCMAKE_INSTALL_PREFIX:PATH=/tmp/pip-build-n6tqv3/cmake/_skbuild/cmake-install/cmake/data" "-DPYTHON_EXECUTABLE:FILEPATH=/home/blowekamp/.virtualenvs/cmake-test/bin/python" "-DPYTHON_VERSION_STRING:STRING=2.7.5" "-DPYTHON_INCLUDE_DIR:PATH=/usr/include/python2.7" "-DPYTHON_LIBRARY:FILEPATH=/usr/lib64/libpython2.7.so" "-DSKBUILD:BOOL=TRUE" "-DCMAKE_MODULE_PATH:PATH=/home/blowekamp/.virtualenvs/cmake-test/lib/python2.7/site-packages/skbuild/resources/cmake" "-DCMAKE_BUILD_TYPE:STRING=Release"
      Source directory:
        /tmp/pip-build-n6tqv3/cmake
      Working directory:
        /tmp/pip-build-n6tqv3/cmake/_skbuild/cmake-build
    Please see CMake's output for more information.
    
    ----------------------------------------
Command "/home/blowekamp/.virtualenvs/cmake-test/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-n6tqv3/cmake/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-WtxxK2-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/blowekamp/.virtualenvs/cmake-test/include/site/python2.7/cmake" failed with error code 1 in /tmp/pip-build-n6tqv3/cmake/
```

**Comment by jcfr** [comment]
@cdeepakroy  I am looking at this now.

**Comment by henryiii** [comment]
FYI, MWE for the above problem (reproduces original message as far as I can tell):
```bash
docker run -it alpine
apk add --no-cache python g++ make
apk add --no-cache cmake # required to use scikit-build on cmake 
python -m ensurepip
pip install --no-binary ":all:" scikit-build
pip install --no-binary ":all:" cmake
```

**Comment by jcfr** [comment]
xref #41

**Comment by jcfr** [comment]
Closing. This was fixed in scikit-build/cmake-python-distributions#41
